# This file is part of yamba which is released under <GPL3>. See file LICENSE or go to https://www.gnu.org/licenses/gpl.html for full license details.

version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
# dev mounts
#      - ./backend/daemon/target/debug:/opt/yamba/daemon/target/debug
#      - ./backend/ts3plugin/target/debug:/opt/yamba/ts3plugin/target/debug
      - ./backend/ts3client:/opt/ts3client
    env_file:
      - ./config/backend.env
    environment:
      yamba_db__host: "${YAMBA_DATABASE_HOST}"
      yamba_db__port: "${YAMBA_DATABASE_PORT}"
      yamba_db__user: "${YAMBA_DATABASE_USER}"
      yamba_db__db: "${YAMBA_DATABASE_DATABASE}"
      yamba_db__password: "${YAMBA_DATABASE_PASSWORD}"
