# This file is part of yamba which is released under <GPL3>. See file LICENSE or go to https://www.gnu.org/licenses/gpl.html for full license details.

version: '3'

services:
  database:
    image: mariadb:10.3.10-bionic
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d
#      - ./database:/var/lib/mysql
    env_file:
      - ./config/database.env
      - ./config/database_root.env
    logging:
      driver: none


  frontend:
    build: ./frontend
    ports:
      - 9000:80
#    volumes:
#      - ./frontend/public_html:/var/www/html
    env_file:
      - ./config/frontend.env
      - ./config/database.env
      - ./config/database_root.env

  backend:
    build: ./backend
    env_file:
      - ./config/backend.env
    environment:
      yamba_db__host: "${MYSQL_HOST}"
      yamba_db__port: "${MYSQL_PORT}"
      yamba_db__user: "${MYSQL_USER}"
      yamba_db__db: "${MYSQL_DATABASE}"
      yamba_db__password: "${MYSQL_PASSWORD}"
