# This file is part of yamba which is released under <GPL3>. See file LICENSE or go to https://www.gnu.org/licenses/gpl.html for full license details.

version: '3'

services:
  database:
    image: mariadb:10.3.10-bionic
    restart: always
    ports:
    - 3306:3306
    volumes:
    - ./dbInit:/docker-entrypoint-initdb.d
    - ./database:/var/lib/mysql
    env_file:
    - ./secrets/database.env

  frontend:
    build: ./frontend
    ports:
      - 9000:80
    volumes:
      - ./downloads:/var/yamba/downloads
      - ./frontend/public_html:/var/www/html
    env_file:
      - ./secrets/frontend.env
      - ./secrets/database.env
  # yamba_backend: