/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import tech.yamba.db.jooq.tables.GroupMembers;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupMembersRecord extends UpdatableRecordImpl<GroupMembersRecord> implements Record2<Short, Short> {

    private static final long serialVersionUID = -745297800;

    /**
     * Setter for <code>public.group_members.user_id</code>.
     */
    public GroupMembersRecord setUserId(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.group_members.user_id</code>.
     */
    public Short getUserId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.group_members.group_id</code>.
     */
    public GroupMembersRecord setGroupId(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.group_members.group_id</code>.
     */
    public Short getGroupId() {
        return (Short) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Short, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Short, Short> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Short, Short> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return GroupMembers.GROUP_MEMBERS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return GroupMembers.GROUP_MEMBERS.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupMembersRecord value1(Short value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupMembersRecord value2(Short value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupMembersRecord values(Short value1, Short value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupMembersRecord
     */
    public GroupMembersRecord() {
        super(GroupMembers.GROUP_MEMBERS);
    }

    /**
     * Create a detached, initialised GroupMembersRecord
     */
    public GroupMembersRecord(Short userId, Short groupId) {
        super(GroupMembers.GROUP_MEMBERS);

        set(0, userId);
        set(1, groupId);
    }
}
