/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import tech.yamba.db.jooq.tables.UserAuthorities;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuthoritiesRecord extends UpdatableRecordImpl<UserAuthoritiesRecord> implements Record2<Short, Short> {

    private static final long serialVersionUID = 1544199218;

    /**
     * Setter for <code>public.user_authorities.user_id</code>.
     */
    public UserAuthoritiesRecord setUserId(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_authorities.user_id</code>.
     */
    public Short getUserId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.user_authorities.authority_id</code>.
     */
    public UserAuthoritiesRecord setAuthorityId(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_authorities.authority_id</code>.
     */
    public Short getAuthorityId() {
        return (Short) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Short, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Short, Short> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Short, Short> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return UserAuthorities.USER_AUTHORITIES.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return UserAuthorities.USER_AUTHORITIES.AUTHORITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getAuthorityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getAuthorityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthoritiesRecord value1(Short value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthoritiesRecord value2(Short value) {
        setAuthorityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthoritiesRecord values(Short value1, Short value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAuthoritiesRecord
     */
    public UserAuthoritiesRecord() {
        super(UserAuthorities.USER_AUTHORITIES);
    }

    /**
     * Create a detached, initialised UserAuthoritiesRecord
     */
    public UserAuthoritiesRecord(Short userId, Short authorityId) {
        super(UserAuthorities.USER_AUTHORITIES);

        set(0, userId);
        set(1, authorityId);
    }
}
