/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import tech.yamba.db.jooq.tables.Authorities;
import tech.yamba.db.jooq.tables.GroupAuthorities;
import tech.yamba.db.jooq.tables.GroupMembers;
import tech.yamba.db.jooq.tables.Groups;
import tech.yamba.db.jooq.tables.UserAuthorities;
import tech.yamba.db.jooq.tables.Users;
import tech.yamba.db.jooq.tables.records.AuthoritiesRecord;
import tech.yamba.db.jooq.tables.records.GroupAuthoritiesRecord;
import tech.yamba.db.jooq.tables.records.GroupMembersRecord;
import tech.yamba.db.jooq.tables.records.GroupsRecord;
import tech.yamba.db.jooq.tables.records.UserAuthoritiesRecord;
import tech.yamba.db.jooq.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuthoritiesRecord, Short> IDENTITY_AUTHORITIES = Identities0.IDENTITY_AUTHORITIES;
    public static final Identity<GroupsRecord, Short> IDENTITY_GROUPS = Identities0.IDENTITY_GROUPS;
    public static final Identity<UsersRecord, Short> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthoritiesRecord> AUTHORITIES_PKEY = UniqueKeys0.AUTHORITIES_PKEY;
    public static final UniqueKey<GroupAuthoritiesRecord> GROUP_AUTHORITIES_PKEY = UniqueKeys0.GROUP_AUTHORITIES_PKEY;
    public static final UniqueKey<GroupMembersRecord> GROUP_MEMBERS_PKEY = UniqueKeys0.GROUP_MEMBERS_PKEY;
    public static final UniqueKey<GroupsRecord> GROUPS_PKEY = UniqueKeys0.GROUPS_PKEY;
    public static final UniqueKey<UserAuthoritiesRecord> USER_AUTHORITIES_PKEY = UniqueKeys0.USER_AUTHORITIES_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = UniqueKeys0.USERS_USERNAME_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GroupAuthoritiesRecord, GroupsRecord> GROUP_AUTHORITIES__GROUP_AUTHORITIES_GROUP_ID_FKEY = ForeignKeys0.GROUP_AUTHORITIES__GROUP_AUTHORITIES_GROUP_ID_FKEY;
    public static final ForeignKey<GroupAuthoritiesRecord, AuthoritiesRecord> GROUP_AUTHORITIES__GROUP_AUTHORITIES_AUTHORITY_ID_FKEY = ForeignKeys0.GROUP_AUTHORITIES__GROUP_AUTHORITIES_AUTHORITY_ID_FKEY;
    public static final ForeignKey<GroupMembersRecord, UsersRecord> GROUP_MEMBERS__GROUP_MEMBERS_USER_ID_FKEY = ForeignKeys0.GROUP_MEMBERS__GROUP_MEMBERS_USER_ID_FKEY;
    public static final ForeignKey<GroupMembersRecord, GroupsRecord> GROUP_MEMBERS__GROUP_MEMBERS_GROUP_ID_FKEY = ForeignKeys0.GROUP_MEMBERS__GROUP_MEMBERS_GROUP_ID_FKEY;
    public static final ForeignKey<UserAuthoritiesRecord, UsersRecord> USER_AUTHORITIES__USER_AUTHORITIES_USER_ID_FKEY = ForeignKeys0.USER_AUTHORITIES__USER_AUTHORITIES_USER_ID_FKEY;
    public static final ForeignKey<UserAuthoritiesRecord, AuthoritiesRecord> USER_AUTHORITIES__USER_AUTHORITIES_AUTHORITY_ID_FKEY = ForeignKeys0.USER_AUTHORITIES__USER_AUTHORITIES_AUTHORITY_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AuthoritiesRecord, Short> IDENTITY_AUTHORITIES = Internal.createIdentity(Authorities.AUTHORITIES, Authorities.AUTHORITIES.ID);
        public static Identity<GroupsRecord, Short> IDENTITY_GROUPS = Internal.createIdentity(Groups.GROUPS, Groups.GROUPS.ID);
        public static Identity<UsersRecord, Short> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthoritiesRecord> AUTHORITIES_PKEY = Internal.createUniqueKey(Authorities.AUTHORITIES, "authorities_pkey", Authorities.AUTHORITIES.ID);
        public static final UniqueKey<GroupAuthoritiesRecord> GROUP_AUTHORITIES_PKEY = Internal.createUniqueKey(GroupAuthorities.GROUP_AUTHORITIES, "group_authorities_pkey", GroupAuthorities.GROUP_AUTHORITIES.GROUP_ID, GroupAuthorities.GROUP_AUTHORITIES.AUTHORITY_ID);
        public static final UniqueKey<GroupMembersRecord> GROUP_MEMBERS_PKEY = Internal.createUniqueKey(GroupMembers.GROUP_MEMBERS, "group_members_pkey", GroupMembers.GROUP_MEMBERS.USER_ID, GroupMembers.GROUP_MEMBERS.GROUP_ID);
        public static final UniqueKey<GroupsRecord> GROUPS_PKEY = Internal.createUniqueKey(Groups.GROUPS, "groups_pkey", Groups.GROUPS.ID);
        public static final UniqueKey<UserAuthoritiesRecord> USER_AUTHORITIES_PKEY = Internal.createUniqueKey(UserAuthorities.USER_AUTHORITIES, "user_authorities_pkey", UserAuthorities.USER_AUTHORITIES.USER_ID, UserAuthorities.USER_AUTHORITIES.AUTHORITY_ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, "users_username_key", Users.USERS.USERNAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<GroupAuthoritiesRecord, GroupsRecord> GROUP_AUTHORITIES__GROUP_AUTHORITIES_GROUP_ID_FKEY = Internal.createForeignKey(tech.yamba.db.jooq.Keys.GROUPS_PKEY, GroupAuthorities.GROUP_AUTHORITIES, "group_authorities__group_authorities_group_id_fkey", GroupAuthorities.GROUP_AUTHORITIES.GROUP_ID);
        public static final ForeignKey<GroupAuthoritiesRecord, AuthoritiesRecord> GROUP_AUTHORITIES__GROUP_AUTHORITIES_AUTHORITY_ID_FKEY = Internal.createForeignKey(tech.yamba.db.jooq.Keys.AUTHORITIES_PKEY, GroupAuthorities.GROUP_AUTHORITIES, "group_authorities__group_authorities_authority_id_fkey", GroupAuthorities.GROUP_AUTHORITIES.AUTHORITY_ID);
        public static final ForeignKey<GroupMembersRecord, UsersRecord> GROUP_MEMBERS__GROUP_MEMBERS_USER_ID_FKEY = Internal.createForeignKey(tech.yamba.db.jooq.Keys.USERS_PKEY, GroupMembers.GROUP_MEMBERS, "group_members__group_members_user_id_fkey", GroupMembers.GROUP_MEMBERS.USER_ID);
        public static final ForeignKey<GroupMembersRecord, GroupsRecord> GROUP_MEMBERS__GROUP_MEMBERS_GROUP_ID_FKEY = Internal.createForeignKey(tech.yamba.db.jooq.Keys.GROUPS_PKEY, GroupMembers.GROUP_MEMBERS, "group_members__group_members_group_id_fkey", GroupMembers.GROUP_MEMBERS.GROUP_ID);
        public static final ForeignKey<UserAuthoritiesRecord, UsersRecord> USER_AUTHORITIES__USER_AUTHORITIES_USER_ID_FKEY = Internal.createForeignKey(tech.yamba.db.jooq.Keys.USERS_PKEY, UserAuthorities.USER_AUTHORITIES, "user_authorities__user_authorities_user_id_fkey", UserAuthorities.USER_AUTHORITIES.USER_ID);
        public static final ForeignKey<UserAuthoritiesRecord, AuthoritiesRecord> USER_AUTHORITIES__USER_AUTHORITIES_AUTHORITY_ID_FKEY = Internal.createForeignKey(tech.yamba.db.jooq.Keys.AUTHORITIES_PKEY, UserAuthorities.USER_AUTHORITIES, "user_authorities__user_authorities_authority_id_fkey", UserAuthorities.USER_AUTHORITIES.AUTHORITY_ID);
    }
}
