/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import tech.yamba.db.jooq.tables.Authorities;
import tech.yamba.db.jooq.tables.GroupAuthorities;
import tech.yamba.db.jooq.tables.GroupMembers;
import tech.yamba.db.jooq.tables.Groups;
import tech.yamba.db.jooq.tables.UserAuthorities;
import tech.yamba.db.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1896386177;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.authorities</code>.
     */
    public final Authorities AUTHORITIES = tech.yamba.db.jooq.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>public.group_authorities</code>.
     */
    public final GroupAuthorities GROUP_AUTHORITIES = tech.yamba.db.jooq.tables.GroupAuthorities.GROUP_AUTHORITIES;

    /**
     * The table <code>public.group_members</code>.
     */
    public final GroupMembers GROUP_MEMBERS = tech.yamba.db.jooq.tables.GroupMembers.GROUP_MEMBERS;

    /**
     * The table <code>public.groups</code>.
     */
    public final Groups GROUPS = tech.yamba.db.jooq.tables.Groups.GROUPS;

    /**
     * The table <code>public.user_authorities</code>.
     */
    public final UserAuthorities USER_AUTHORITIES = tech.yamba.db.jooq.tables.UserAuthorities.USER_AUTHORITIES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = tech.yamba.db.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.AUTHORITIES_ID_SEQ,
            Sequences.GROUPS_ID_SEQ,
            Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authorities.AUTHORITIES,
            GroupAuthorities.GROUP_AUTHORITIES,
            GroupMembers.GROUP_MEMBERS,
            Groups.GROUPS,
            UserAuthorities.USER_AUTHORITIES,
            Users.USERS);
    }
}
