/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq;


import javax.annotation.Generated;

import tech.yamba.db.jooq.tables.Authorities;
import tech.yamba.db.jooq.tables.GroupAuthorities;
import tech.yamba.db.jooq.tables.GroupMembers;
import tech.yamba.db.jooq.tables.Groups;
import tech.yamba.db.jooq.tables.Instances;
import tech.yamba.db.jooq.tables.UserAuthorities;
import tech.yamba.db.jooq.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.authorities</code>.
     */
    public static final Authorities AUTHORITIES = tech.yamba.db.jooq.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>public.group_authorities</code>.
     */
    public static final GroupAuthorities GROUP_AUTHORITIES = tech.yamba.db.jooq.tables.GroupAuthorities.GROUP_AUTHORITIES;

    /**
     * The table <code>public.group_members</code>.
     */
    public static final GroupMembers GROUP_MEMBERS = tech.yamba.db.jooq.tables.GroupMembers.GROUP_MEMBERS;

    /**
     * The table <code>public.groups</code>.
     */
    public static final Groups GROUPS = tech.yamba.db.jooq.tables.Groups.GROUPS;

    /**
     * The table <code>public.instances</code>.
     */
    public static final Instances INSTANCES = tech.yamba.db.jooq.tables.Instances.INSTANCES;

    /**
     * The table <code>public.user_authorities</code>.
     */
    public static final UserAuthorities USER_AUTHORITIES = tech.yamba.db.jooq.tables.UserAuthorities.USER_AUTHORITIES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = tech.yamba.db.jooq.tables.Users.USERS;
}
