/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tech.yamba.db.jooq.Indexes;
import tech.yamba.db.jooq.Keys;
import tech.yamba.db.jooq.Public;
import tech.yamba.db.jooq.tables.records.GroupAuthoritiesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupAuthorities extends TableImpl<GroupAuthoritiesRecord> {

    private static final long serialVersionUID = -899005311;

    /**
     * The reference instance of <code>public.group_authorities</code>
     */
    public static final GroupAuthorities GROUP_AUTHORITIES = new GroupAuthorities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupAuthoritiesRecord> getRecordType() {
        return GroupAuthoritiesRecord.class;
    }

    /**
     * The column <code>public.group_authorities.group_id</code>.
     */
    public final TableField<GroupAuthoritiesRecord, Short> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.group_authorities.authority_id</code>.
     */
    public final TableField<GroupAuthoritiesRecord, Short> AUTHORITY_ID = createField("authority_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * Create a <code>public.group_authorities</code> table reference
     */
    public GroupAuthorities() {
        this(DSL.name("group_authorities"), null);
    }

    /**
     * Create an aliased <code>public.group_authorities</code> table reference
     */
    public GroupAuthorities(String alias) {
        this(DSL.name(alias), GROUP_AUTHORITIES);
    }

    /**
     * Create an aliased <code>public.group_authorities</code> table reference
     */
    public GroupAuthorities(Name alias) {
        this(alias, GROUP_AUTHORITIES);
    }

    private GroupAuthorities(Name alias, Table<GroupAuthoritiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GroupAuthorities(Name alias, Table<GroupAuthoritiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GroupAuthorities(Table<O> child, ForeignKey<O, GroupAuthoritiesRecord> key) {
        super(child, key, GROUP_AUTHORITIES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUP_AUTHORITIES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GroupAuthoritiesRecord> getPrimaryKey() {
        return Keys.GROUP_AUTHORITIES_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GroupAuthoritiesRecord>> getKeys() {
        return Arrays.<UniqueKey<GroupAuthoritiesRecord>>asList(Keys.GROUP_AUTHORITIES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GroupAuthoritiesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GroupAuthoritiesRecord, ?>>asList(Keys.GROUP_AUTHORITIES__GROUP_AUTHORITIES_GROUP_ID_FKEY, Keys.GROUP_AUTHORITIES__GROUP_AUTHORITIES_AUTHORITY_ID_FKEY);
    }

    public Groups groups() {
        return new Groups(this, Keys.GROUP_AUTHORITIES__GROUP_AUTHORITIES_GROUP_ID_FKEY);
    }

    public Authorities authorities() {
        return new Authorities(this, Keys.GROUP_AUTHORITIES__GROUP_AUTHORITIES_AUTHORITY_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupAuthorities as(String alias) {
        return new GroupAuthorities(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupAuthorities as(Name alias) {
        return new GroupAuthorities(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupAuthorities rename(String name) {
        return new GroupAuthorities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupAuthorities rename(Name name) {
        return new GroupAuthorities(name, null);
    }
}
