/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tech.yamba.db.jooq.Indexes;
import tech.yamba.db.jooq.Keys;
import tech.yamba.db.jooq.Public;
import tech.yamba.db.jooq.tables.records.GroupMembersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupMembers extends TableImpl<GroupMembersRecord> {

    private static final long serialVersionUID = 565721142;

    /**
     * The reference instance of <code>public.group_members</code>
     */
    public static final GroupMembers GROUP_MEMBERS = new GroupMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupMembersRecord> getRecordType() {
        return GroupMembersRecord.class;
    }

    /**
     * The column <code>public.group_members.user_id</code>.
     */
    public final TableField<GroupMembersRecord, Short> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.group_members.group_id</code>.
     */
    public final TableField<GroupMembersRecord, Short> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * Create a <code>public.group_members</code> table reference
     */
    public GroupMembers() {
        this(DSL.name("group_members"), null);
    }

    /**
     * Create an aliased <code>public.group_members</code> table reference
     */
    public GroupMembers(String alias) {
        this(DSL.name(alias), GROUP_MEMBERS);
    }

    /**
     * Create an aliased <code>public.group_members</code> table reference
     */
    public GroupMembers(Name alias) {
        this(alias, GROUP_MEMBERS);
    }

    private GroupMembers(Name alias, Table<GroupMembersRecord> aliased) {
        this(alias, aliased, null);
    }

    private GroupMembers(Name alias, Table<GroupMembersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GroupMembers(Table<O> child, ForeignKey<O, GroupMembersRecord> key) {
        super(child, key, GROUP_MEMBERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUP_MEMBERS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GroupMembersRecord> getPrimaryKey() {
        return Keys.GROUP_MEMBERS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GroupMembersRecord>> getKeys() {
        return Arrays.<UniqueKey<GroupMembersRecord>>asList(Keys.GROUP_MEMBERS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GroupMembersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GroupMembersRecord, ?>>asList(Keys.GROUP_MEMBERS__GROUP_MEMBERS_USER_ID_FKEY, Keys.GROUP_MEMBERS__GROUP_MEMBERS_GROUP_ID_FKEY);
    }

    public Users users() {
        return new Users(this, Keys.GROUP_MEMBERS__GROUP_MEMBERS_USER_ID_FKEY);
    }

    public Groups groups() {
        return new Groups(this, Keys.GROUP_MEMBERS__GROUP_MEMBERS_GROUP_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupMembers as(String alias) {
        return new GroupMembers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupMembers as(Name alias) {
        return new GroupMembers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMembers rename(String name) {
        return new GroupMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMembers rename(Name name) {
        return new GroupMembers(name, null);
    }
}
