/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authority implements Serializable {

    private static final long serialVersionUID = 1880525530;

    private Short  id;
    private String authority;

    public Authority() {}

    public Authority(Authority value) {
        this.id = value.id;
        this.authority = value.authority;
    }

    public Authority(
        Short  id,
        String authority
    ) {
        this.id = id;
        this.authority = authority;
    }

    public Short getId() {
        return this.id;
    }

    public Authority setId(Short id) {
        this.id = id;
        return this;
    }

    public String getAuthority() {
        return this.authority;
    }

    public Authority setAuthority(String authority) {
        this.authority = authority;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Authority other = (Authority) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (authority == null) {
            if (other.authority != null)
                return false;
        }
        else if (!authority.equals(other.authority))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.authority == null) ? 0 : this.authority.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Authority (");

        sb.append(id);
        sb.append(", ").append(authority);

        sb.append(")");
        return sb.toString();
    }
}
