/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupAuthority implements Serializable {

    private static final long serialVersionUID = -85654839;

    private Short groupId;
    private Short authorityId;

    public GroupAuthority() {}

    public GroupAuthority(GroupAuthority value) {
        this.groupId = value.groupId;
        this.authorityId = value.authorityId;
    }

    public GroupAuthority(
        Short groupId,
        Short authorityId
    ) {
        this.groupId = groupId;
        this.authorityId = authorityId;
    }

    @NotNull
    public Short getGroupId() {
        return this.groupId;
    }

    public GroupAuthority setGroupId(Short groupId) {
        this.groupId = groupId;
        return this;
    }

    @NotNull
    public Short getAuthorityId() {
        return this.authorityId;
    }

    public GroupAuthority setAuthorityId(Short authorityId) {
        this.authorityId = authorityId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GroupAuthority other = (GroupAuthority) obj;
        if (groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!groupId.equals(other.groupId))
            return false;
        if (authorityId == null) {
            if (other.authorityId != null)
                return false;
        }
        else if (!authorityId.equals(other.authorityId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        result = prime * result + ((this.authorityId == null) ? 0 : this.authorityId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupAuthority (");

        sb.append(groupId);
        sb.append(", ").append(authorityId);

        sb.append(")");
        return sb.toString();
    }
}
