/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupMember implements Serializable {

    private static final long serialVersionUID = -18116167;

    private Short userId;
    private Short groupId;

    public GroupMember() {}

    public GroupMember(GroupMember value) {
        this.userId = value.userId;
        this.groupId = value.groupId;
    }

    public GroupMember(
        Short userId,
        Short groupId
    ) {
        this.userId = userId;
        this.groupId = groupId;
    }

    @NotNull
    public Short getUserId() {
        return this.userId;
    }

    public GroupMember setUserId(Short userId) {
        this.userId = userId;
        return this;
    }

    @NotNull
    public Short getGroupId() {
        return this.groupId;
    }

    public GroupMember setGroupId(Short groupId) {
        this.groupId = groupId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GroupMember other = (GroupMember) obj;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!groupId.equals(other.groupId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupMember (");

        sb.append(userId);
        sb.append(", ").append(groupId);

        sb.append(")");
        return sb.toString();
    }
}
