/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import tech.yamba.db.jooq.tables.Users;
import tech.yamba.db.jooq.tables.pojos.User;
import tech.yamba.db.jooq.tables.records.UsersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UsersDao extends DAOImpl<UsersRecord, User, Short> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, User.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    @Autowired
    public UsersDao(Configuration configuration) {
        super(Users.USERS, User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Short getId(User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<User> fetchById(Short... values) {
        return fetch(Users.USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public User fetchOneById(Short value) {
        return fetchOne(Users.USERS.ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<User> fetchByUsername(String... values) {
        return fetch(Users.USERS.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public User fetchOneByUsername(String value) {
        return fetchOne(Users.USERS.USERNAME, value);
    }

    /**
     * Fetch records that have <code>enabled IN (values)</code>
     */
    public List<User> fetchByEnabled(Boolean... values) {
        return fetch(Users.USERS.ENABLED, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<User> fetchByPassword(String... values) {
        return fetch(Users.USERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<User> fetchByCreated(Timestamp... values) {
        return fetch(Users.USERS.CREATED, values);
    }
}
