/*
 * This file is generated by jOOQ.
 */
package tech.yamba.db.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import tech.yamba.db.jooq.tables.UserAuthorities;
import tech.yamba.db.jooq.tables.pojos.UserAuthority;
import tech.yamba.db.jooq.tables.records.UserAuthoritiesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserAuthoritiesDao extends DAOImpl<UserAuthoritiesRecord, UserAuthority, Record2<Short, Short>> {

    /**
     * Create a new UserAuthoritiesDao without any configuration
     */
    public UserAuthoritiesDao() {
        super(UserAuthorities.USER_AUTHORITIES, UserAuthority.class);
    }

    /**
     * Create a new UserAuthoritiesDao with an attached configuration
     */
    @Autowired
    public UserAuthoritiesDao(Configuration configuration) {
        super(UserAuthorities.USER_AUTHORITIES, UserAuthority.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Short, Short> getId(UserAuthority object) {
        return compositeKeyRecord(object.getUserId(), object.getAuthorityId());
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<UserAuthority> fetchByUserId(Short... values) {
        return fetch(UserAuthorities.USER_AUTHORITIES.USER_ID, values);
    }

    /**
     * Fetch records that have <code>authority_id IN (values)</code>
     */
    public List<UserAuthority> fetchByAuthorityId(Short... values) {
        return fetch(UserAuthorities.USER_AUTHORITIES.AUTHORITY_ID, values);
    }
}
