[package]
name = "yamba-backend"
version = "0.1.0"
authors = ["Aron Heinecke <aron.heinecke@t-online.de>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
clap = "2"
log = "0.4"
slog = "2.4"
slog-scope = "4.0"
slog-stdlog = "3.0"
slog-term = "2.4"
slog-async = "2.3"
lazy_static = "1.1"
glob = "0.2"
config = "0.9"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
json = "0.11"
sha2 = "0.8"

[dependencies.vlc-rs]
git = "https://github.com/0xpr03/vlc-rs"
branch = "merge_master"
